# Generated by Django 5.1.5 on 2025-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('url', 'URL'), ('hash', 'Hash'), ('file', 'File'), ('ip', 'IP Address')], max_length=10)),
                ('input_value', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('is_malicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
